version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: museum-map-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: museum_map
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
